### ISSUE TITLE
SEP10: Transaction is immutable

### ISSUE THREAD

**Issue by alpe** [stellar-deprecated/transfer-server-validator#193]
### What version are you using?

* Node: v14.15.4
* stellar-sdk@^5.0.4:

### What did you do?
`npx jest -I -i cases-SEP6/sep10.test.js`

### What did you expect to see?
👍 

### What did you see instead?
```
● SEP10 › GET Challenge › POST Response › fails if the signed challenge isn't signed by the servers SIGNING_KEY

    Transaction is immutable

      257 |         );
      258 |         // Remove the server signature, only sign by client
    > 259 |         tx.signatures = [];
          |         ^
      260 |         tx.sign(keyPair);
      261 |         let { json: tokenJson, status, logs } = await loggableFetch(
      262 |           toml.WEB_AUTH_ENDPOINT,

      at Transaction.set (node_modules/stellar-base/lib/transaction_base.js:220:13)
      at Object.<anonymous> (cases-SEP6/sep10.test.js:259:9)
```

**Comment by JakeUrban** [comment]
This bug was fixed, thanks for reporting!
