### ISSUE TITLE
Fix StaleElementReferenceError bug

### ISSUE THREAD

**Issue by JakeUrban** [stellar-deprecated/transfer-server-validator#68]
This error happens every-so-often during interactive tests. If one fails, the rest do, so this increases the urgency. I'm guessing this happens because we're not waiting long enough for the page to load? Will have to debug.
```
StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: headless chrome=80.0.3987.132)
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:563:13)
    at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Driver.execute (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:699:17)
```

**Comment by vitchor** [comment]
I've just got this error in the interactive tests. Do you have any clues on what's happening there @JakeUrban ?

**Comment by JakeUrban** [comment]
Not specifically, but the gist is that we selected an HTML element in the javascript which is no longer on the page. Its hard to reproduce so I haven't made much progress.
